### ISSUE TITLE
upgrade `@nesjts/common` peer dependency to v7 from v6

### ISSUE THREAD

**Issue by micalevisk** [iamolegga/create-nestjs-middleware-module#257]
https://github.com/iamolegga/create-nestjs-middleware-module/blob/2ab8f99d23c221ec6684802f67f67307680ec4cf/package.json#L29-L30
https://github.com/iamolegga/create-nestjs-middleware-module/blob/2ab8f99d23c221ec6684802f67f67307680ec4cf/package.json#L49-L51

I've been using this lib with `@nesjts/common@7.4.4` with no worries. I read the [migration guide](https://docs.nestjs.com/migration-guide) as well.

**Comment by micalevisk** [comment]
ping.

I've been using with `@nestjs/common@7.6.5` to address [this issue](https://github.com/nestjs/passport/issues/236) with no worries :)

**Comment by TrejGun** [comment]
this is actually broken with latest 7.6.14

**Comment by micalevisk** [comment]
Hey @TrejGun can you describe how the error manifests? I'm using with 7.6.14

**Comment by TrejGun** [comment]
sorry it was my mistake. it works.

**Comment by micalevisk** [comment]
I've run `npm t` locally after using v7.6.5 of all `@nestjs/*` dev. dependencies, and got 1 test failure tho:

```
 FAIL  __tests__/tests.spec.ts (8.851s)
  ExpressAdapter
    ✓ empty forRoot() and casting to FacadeModuleStaticOptional<T> calls with empty object (96ms)
    ✓ forRoot() arguments are correct (23ms)
    ✓ forRootAsync() arguments are correct (19ms)
    ✓ createModule callback returning array works correct (19ms)
    ✓ routing arguments are correct (33ms)
  FastifyAdapter
    ✓ empty forRoot() and casting to FacadeModuleStaticOptional<T> calls with empty object (180ms)
    ✓ forRoot() arguments are correct (48ms)
    ✓ forRootAsync() arguments are correct (50ms)
    ✓ createModule callback returning array works correct (44ms)
    ✕ routing arguments are correct (57ms)

  ● FastifyAdapter › routing arguments are correct

    expect(jest.fn()).toHaveBeenCalledTimes(expected)

    Expected number of calls: 1
    Received number of calls: 2

      208 | 
      209 |       expect(createMiddleware).toHaveBeenCalledWith(params);
    > 210 |       expect(countFn).toHaveBeenCalledTimes(1);
          |                       ^
      211 |     });
      212 |   });
      213 | }

      at Object.<anonymous> (__tests__/tests.spec.ts:210:23)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |     100 |      100 |     100 |     100 |                   
 index.ts |     100 |      100 |     100 |     100 |                   
----------|---------|----------|---------|---------|-------------------
Test Suites: 1 failed, 1 total
Tests:       1 failed, 9 passed, 10 total
Snapshots:   0 total
Time:        9.343s, estimated 10s
Ran all test suites.
```

**Comment by micalevisk** [comment]
> I've run `npm t` locally after using v7.6.5 of all `@nestjs/*` dev. dependencies, and got 1 test failure tho:
> 
> ```
>  FAIL  __tests__/tests.spec.ts (8.851s)
>   ExpressAdapter
>     ✓ empty forRoot() and casting to FacadeModuleStaticOptional<T> calls with empty object (96ms)
>     ✓ forRoot() arguments are correct (23ms)
>     ✓ forRootAsync() arguments are correct (19ms)
>     ✓ createModule callback returning array works correct (19ms)
>     ✓ routing arguments are correct (33ms)
>   FastifyAdapter
>     ✓ empty forRoot() and casting to FacadeModuleStaticOptional<T> calls with empty object (180ms)
>     ✓ forRoot() arguments are correct (48ms)
>     ✓ forRootAsync() arguments are correct (50ms)
>     ✓ createModule callback returning array works correct (44ms)
>     ✕ routing arguments are correct (57ms)
> 
>   ● FastifyAdapter › routing arguments are correct
> 
>     expect(jest.fn()).toHaveBeenCalledTimes(expected)
> 
>     Expected number of calls: 1
>     Received number of calls: 2
> 
>       208 | 
>       209 |       expect(createMiddleware).toHaveBeenCalledWith(params);
>     > 210 |       expect(countFn).toHaveBeenCalledTimes(1);
>           |                       ^
>       211 |     });
>       212 |   });
>       213 | }
> 
>       at Object.<anonymous> (__tests__/tests.spec.ts:210:23)
> 
> ----------|---------|----------|---------|---------|-------------------
> File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
> ----------|---------|----------|---------|---------|-------------------
> All files |     100 |      100 |     100 |     100 |                   
>  index.ts |     100 |      100 |     100 |     100 |                   
> ----------|---------|----------|---------|---------|-------------------
> Test Suites: 1 failed, 1 total
> Tests:       1 failed, 9 passed, 10 total
> Snapshots:   0 total
> Time:        9.343s, estimated 10s
> Ran all test suites.
> ```
> 
> you could try this version in my fork [here](https://github.com/micalevisk/create-nestjs-middleware-module/tree/594e8e08eb56260862685b37a2d66e9fab627d8b)

I've notice that `.exclude('foo').forRoutes(FooController)` in v7 does not work in the same way for both http adapters, this is why that test didn't pass.

**Comment by micalevisk** [comment]
@iamolegga This was fixed in Nest 8.0.5, thus `create-nestjs-middleware-module` is compatible with v6 and v8. I tested it in my fork [here on branch `use-nestjs-v8`](https://github.com/micalevisk/create-nestjs-middleware-module/tree/use-nestjs-v8).

**Comment by iamolegga** [comment]
@micalevisk  thanks, will get back to this soon, as it's not so urgent and can be solved with `--legacy-peer-deps` now. I'm going to update all the things in the next month

**Comment by iamolegga** [comment]
just released new version, tested on new version of `nestjs-session`, installed to nest@8 project without any errors. closing
