### ISSUE TITLE
remove FacadeModule

### ISSUE THREAD

**Issue by TrejGun** [iamolegga/create-nestjs-middleware-module#364]
FacadeModule seems to be redundant. 
I was not patient enough and migrated this module to nest8 a long time ago. 
As a part of the migration, I got rid of FacadeModule and it seems to work fine without it.
Maybe you consider removing it too

**Comment by iamolegga** [comment]
thanks for the advice, already get rid of the facade in `nestjs-pino`, will consider in current one too

**Comment by iamolegga** [comment]
solved in `0.3.0`
