### ISSUE TITLE
Add some description to `optionsToken` symbol

### ISSUE THREAD

**Issue by micalevisk** [iamolegga/create-nestjs-middleware-module#463]
when using `NEST_DEBUG=true` on NestJS `8.2.0`, the following line will crashes the app due to this bug: https://github.com/nestjs/nest/issues/8560

https://github.com/iamolegga/create-nestjs-middleware-module/blob/045b3ec17b4c486e0d6d95d55671e093dbf1bf57/src/index.ts#L49

this isn't the problem, tho.

---

What do you think of changing that symbol to `Symbol('create-nestjs-middleware-module:options')` or something? I guess this will help people on debugging nestjs's resolutions 

For now we'll get (after Nest `8.2.1`) an entry like

```
... Resolving dependency FooToken in the Symbol() provider
```

**Comment by iamolegga** [comment]
Thanks, good idea! Would you like to contribute?
